name: "[Arch] Build (Clang)"
on:
  push:
#    branches: [ main ]

concurrency:
  group: check-build-self-hosted
  cancel-in-progress: false

jobs:
  call-build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: arch
      branch: main
    secrets:
      PRAGMA_TESTS_IMPORT_TOKEN: ${{ secrets.PRAGMA_TESTS_IMPORT_TOKEN }}
