name: "[Ubuntu] Build (GCC)"
# Note: Due to ongoing GCC compiler errors with C++20 modules, this workflow will likely fail. Once the compiler errors have been resolved, this should be changed to on: push.
on:
  workflow_dispatch:

concurrency:
  group: check-build-lin-gcc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: ubuntu-latest
      build-args: '--c-compiler=gcc --cxx-compiler=g++'
    secrets:
      PRAGMA_TESTS_IMPORT_TOKEN: ${{ secrets.PRAGMA_TESTS_IMPORT_TOKEN }}
