name: "[Windows] Build and Release (Clang)"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-and-release-win-clang-${{ github.ref }}
  cancel-in-progress: true