name: "[Windows] Build (MSVC)"
# Note: Building with MSVC will hit the GitHub runner time limit for workflow jobs, due to long build times. This is likely due to MSVC compiler bugs with C++20 modules.
# Once these issues have been resolved, this should be changed to on: push.
on:
  workflow_dispatch:

concurrency:
  group: check-build-win-msvc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      os: windows-latest
      build-args: '--toolset=msvc'
    secrets:
      PRAGMA_TESTS_IMPORT_TOKEN: ${{ secrets.PRAGMA_TESTS_IMPORT_TOKEN }}
